---
driver_plugin: docker
driver_config:
  docker_path: lxc-docker

platforms:
- name: ubuntu-12.10
  driver_config:
    image: ubuntu:12.10
    platform: ubuntu
  run_list:
  - recipe[apt]

- name: debian-6.0.7
  driver_config:
    image: tianon/debian:6.0.7
    platform: debian
  run_list:
  - recipe[apt]

suites:
- name: install_package
  run_list:
  - recipe[prosody]
  - recipe[prosody-test]
  - recipe[minitest-handler]
  attributes:

- name: install_source
  run_list:
  - recipe[prosody]
  - recipe[prosody-test]
  attributes: 
    prosody:
      install_type: "source"

- name: install_git
  run_list:
  - recipe[prosody]
  - recipe[prosody-test]
  attributes:
    prosody:
      install_type: "git"

- name: ldap_auth
  run_list:
  - recipe[prosody]
  - recipe[prosody-test]
  attributes:
    prosody:
      authentication: "ldap"
#      catchall: "cf"
