---
driver_plugin: vagrant
driver_config:
    require_chef_omnibus: 11.6.2

platforms:
- name: ubuntu-12.10
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: debian-7
  driver_config:
    box: opscode-debian-7.1
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_debian-7.1.0_provisionerless.box
  run_list:
  - recipe[apt]

suites:
- name: from_package
  run_list:
  - recipe[prosody]
  - recipe[prosody-test]
  - recipe[minitest-handler]
  attributes:
      install_type: "package"

- name: from_source
  run_list:
  - recipe[prosody]
  - recipe[prosody-test]
  - recipe[minitest-handler]
  attributes:
    prosody:
      install_type: "source"

- name: from_git
  run_list:
  - recipe[prosody]
  - recipe[prosody-test]
  - recipe[minitest-handler]
  attributes:
    prosody:
      install_type: "git"

- name: ldap_auth
  run_list:
  - recipe[prosody]
  - recipe[prosody-test]
  - recipe[minitest-handler]
  attributes:
    prosody:
      install_type: "package"
      authentication: "ldap"
#      catchall: "myCatchall"
